### PR TITLE
Implement layout of Home page

### PR DESCRIPTION
**Pull request by MeriM-dev**
Added custom css button types.
Added a dummy chart.
Added user info, a chart of market and action buttons on Home page.

### CODE REVIEW

**Review by krismutalapova — CHANGES_REQUESTED** [review]
Hey, Meri! That's what I get when I fetch your branch: 
Failed to compile
./src/components/DummyChart.js
Module not found: Can't resolve 'mdbreact' in '/Users/kris.mutalapova/Documents/Coding/nysure_web_application/frontend/src/components'

**Review by krismutalapova — APPROVED** [review]
You need to install npm install --save mdbreact in your frontend folder to make it work

**Comment by mabmalia** [comment]
It's working on Kris laptop. But on mine, I click on the register button and everything goes black. The homepage probably is ok, but I can't get there.

**Comment by parpinelopi** [comment]
It looks very good and everything works when you install the nbdreact

**Review by elmenqui — APPROVED** [review]
After much debugging, it works. 
The issue was a CSS overwrite in index.html. It is not an elegant fix but it works

**Pull request merged**
