### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by elmenqui**
v0.1
  - Page opens from NavBar Link

 
Still missing:
 - Set/Get correctly in the backend
 - Layout improvements

### CODE REVIEW

**Review by SaraGarabedian — APPROVED** [review]
Fails where expected

**Review by krismutalapova — COMMENTED** [review]
Looking pretty, tho shouldn't we approve it when it stops throwing errors? :)

**Comment by parpinelopi** [comment]
Looks really cool. However, I get this when I try to edit. 

  </div>
  87 |     <button type="button"
  88 |         className="btn"
> 89 |         onClick={e => onSubmit({phone})}    <-----error
  90 |             <i className="edit-info"></i>
  91 |     </button>
  92 | </div>

**Review by parpinelopi — APPROVED** [review]
The layout is nice. Functionality can be added gradually.

**Pull request merged**
