### PR TITLE
Tests for Registration of new user

### PR DESCRIPTION
**Pull request by SaraGarabedian**

### CODE REVIEW

**Review by mabmalia — COMMENTED** [review]
Is it normal that some tests throw exceptions?

se.kth.sda6.nysure.auth.RegisterUserAPITest > negativePasswordRegisterUserAPI() FAILED
    org.springframework.dao.DataIntegrityViolationException at RegisterUserAPITest.java:118
        Caused by: org.hibernate.exception.ConstraintViolationException at RegisterUserAPITest.java:118
            Caused by: org.postgresql.util.PSQLException at RegisterUserAPITest.java:118
se.kth.sda6.nysure.auth.RegisterUserAPITest > negativeAddressRegisterUserAPI() FAILED
    org.springframework.dao.DataIntegrityViolationException at RegisterUserAPITest.java:196
        Caused by: org.hibernate.exception.ConstraintViolationException at RegisterUserAPITest.java:196
            Caused by: org.postgresql.util.PSQLException at RegisterUserAPITest.java:196
se.kth.sda6.nysure.auth.RegisterUserAPITest > positiveRegisterUserAPI() FAILED
    org.springframework.dao.DataIntegrityViolationException at RegisterUserAPITest.java:50
        Caused by: org.hibernate.exception.ConstraintViolationException at RegisterUserAPITest.java:50
            Caused by: org.postgresql.util.PSQLException at RegisterUserAPITest.java:50
se.kth.sda6.nysure.auth.RegisterUserAPITest > negativeNameRegisterUserAPI() FAILED
    org.springframework.dao.DataIntegrityViolationException at RegisterUserAPITest.java:163
        Caused by: org.hibernate.exception.ConstraintViolationException at RegisterUserAPITest.java:163
            Caused by: org.postgresql.util.PSQLException at RegisterUserAPITest.java:163
se.kth.sda6.nysure.auth.RegisterUserAPITest > negativePhoneNumberRegisterUserAPI() FAILED
    org.springframework.dao.DataIntegrityViolationException at RegisterUserAPITest.java:229
        Caused by: org.hibernate.exception.ConstraintViolationException at RegisterUserAPITest.java:229
            Caused by: org.postgresql.util.PSQLException at RegisterUserAPITest.java:229

**Comment by SaraGarabedian** [comment]
The necessary changes have been made, 
The test will still break on 3 methods, which is normal. This indicates that the corresponding code must be fixed

**Review by krismutalapova — APPROVED** [review]
LGTM

**Review by mabmalia — APPROVED** [review]
Have some concerns abt this message: "FAILURE: Build failed with an exception.", but will approve it anyway.

**Pull request merged**
