### PR TITLE
favicon changed to match our logo

### PR DESCRIPTION
**Pull request by elmenqui**
Changed the favicon to match our webapp logo "Nysure"

### CODE REVIEW

**Review by mabmalia — COMMENTED** [review]
Could the favicon be just the house? Because no one will be able to read what is below it.

**Review by krismutalapova — COMMENTED** [review]
I think we don't need the name of the company only the logo and a bit bigger than it is right now

**Comment by elmenqui** [comment]
Changes made

**Review by SaraGarabedian — APPROVED** [review]
Favicon appears properly

**Review by krismutalapova — APPROVED** [review]

**Pull request merged**
