### PR TITLE
Get balance in the homepage

### PR DESCRIPTION
**Pull request by mabmalia**
Fixed some minor issues and in the homepage the balance is calculated according to the active insurances cost in the insurance page. If you add a new insurance, you should be able to see the balance updating.

### CODE REVIEW

**Review by SaraGarabedian — COMMENTED** [review]
OK: The balance starts at 0 sek
Issue: When I try to add an insurance, I get an error message, even after I add items in every category;
This error already exists in Master, therefore, I'd like your confirmation it is expected before approval, because I can't test the incremental function
Screenshot 2019-12-13 at 05 33 07

**Comment by krismutalapova** [comment]
@SaraGarabedian it's probably because you're logging in with the account which doesn't exist in the database and the alert message was added on purpose to inform that the user doesn't have the insurance(or in our case the  insurance doesn't exist in the DB) try with the existing account :)

**Review by krismutalapova — CHANGES_REQUESTED** [review]
For mer works fine, when I log in I have 2 insurances and the balance is correct 
Screenshot 2019-12-13 at 07 09 01
Screenshot 2019-12-13 at 07 09 08

When I add insurances the balance changes 
Screenshot 2019-12-13 at 07 08 30
Screenshot 2019-12-13 at 07 08 37


BUT The branch has a conflict now so has to be updated :(

**Comment by mabmalia** [comment]
Sara, that is not an issue, is a feature implemented yesterday. :) You don't have new insurances to be fetched from the DB (in the future we would fetch this info from insurances companies). Or you use one of the users in data.sql file or you need to add insurances in the DB or data.sql file with the personnummer of the user you are using.

**Comment by mabmalia** [comment]
I am going to update the branch first.

**Comment by SaraGarabedian** [comment]
Miguel: saw both your messages, thank you for the reminder, sorry about that!

**Comment by mabmalia** [comment]
I have updated the branch @SaraGarabedian and @krismutalapova .

**Review by MeriM-dev — APPROVED** [review]
LGTM

**Review by SaraGarabedian — APPROVED** [review]
Works as intended

**Review by elmenqui — APPROVED** [review]
LGTM

**Review by krismutalapova — APPROVED** [review]

**Pull request merged**
