### PR TITLE
Claim backend

### PR DESCRIPTION
**Pull request by krismutalapova**
backend for Claims implemented

### CODE REVIEW

**Review by mabmalia — CHANGES_REQUESTED** [review]
Can't run the backend, an error is thrown:

Error creating bean with name 'claimRepository': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Failed to create query for method public abstract java.util.List se.kth.sda6.nysure.claim.ClaimRepository.findAllByUser(se.kth.sda6.nysure.user.User)! No property user found for type Claim!

**Review by elmenqui — APPROVED** [review]
LGTM

**Review by mabmalia — APPROVED** [review]

**Comment by mabmalia** [comment]
Was missing a field User in the Claim class. Problem was fixed.

**Comment by parpinelopi** [comment]
I was about to check and ...boom merged. I will update master and my branch and check.

**Pull request merged**
