### PR TITLE
Insurance and item fixes

### PR DESCRIPTION
**Pull request by mabmalia**
Item and Insurance are now linked to a user.

Item form fetches the available insurances.

Fixed some minor bugs.

Buttons from the homepage don't work properly only the ones in the nav bar. Alberto may have a solution for it. Gonna look at it.

### CODE REVIEW

**Comment by mabmalia** [comment]
Bear in mind that, there's a data.sql file that contains 2 users and the insurances available to those users.

We need to implement an alert message because you will only be able to fetch insurance information if the user has an insurance with that company (in this case, in the DB).

**Review by krismutalapova — APPROVED** [review]
LGTM

**Review by SaraGarabedian — APPROVED** [review]
Works as described

**Review by elmenqui — APPROVED** [review]
LGTM

**Pull request merged**
