### PR TITLE
Trello-106: Create a class for User

### PR DESCRIPTION
**Pull request by MeriM-dev**
Updated the Id type of User to be String instead of Long, and is no longer autogenerated.
Added address and phone as additional fields.

[trello](https://trello.com/c/ispBd7YA/106-prior-1-create-a-class-for-user)

### CODE REVIEW

**Comment by parpinelopi** [comment]
I also took a look at it. :) If I am not mistaken in the user class getter and setter method for the phone might be missing.

**Comment by MeriM-dev** [comment]
> I also took a look at it. :) If I am not mistaken in the user class getter and setter method for the phone might be missing.

Done, fixed for phone and address.

**Review by elmenqui — APPROVED** [review]
LGTM

**Comment by Pinelopi85** [comment]
It seems fine now Meri.

**Review by parpinelopi — APPROVED** [review]
Looks fine now.

**Pull request merged**
