### PR TITLE
Profile page update

### PR DESCRIPTION
**Pull request by elmenqui**
Access profile page via the edit icon on TopBar

Update name, email and password in Profile Page

### CODE REVIEW

**Comment by mabmalia** [comment]
ERROR message when inspecting the page:

Warning: Received `true` for a non-boolean attribute `div`.

If you want to write it to the DOM, pass a string instead: div="true" or div={value.toString()}.
    in div (at ProfileForm.js:57)

**Comment by mabmalia** [comment]
This error appeared when I tried to change my email. I'm logged out of the app.

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ProfileForm (at ProfilePage.js:23)

**Comment by parpinelopi** [comment]
After changing the email, we are redirected to login page, so maybe this needs to be fixed.  The layout can be fixed until Monday.

**Review by mabmalia — COMMENTED** [review]
The functionality of the edit button is not intuitive.
It's throwing errors that you can see in inspect.
It logs out when you change the email.
The password box is empty.

**Pull request closed without merging**
