### PR TITLE
Modified the Login page and subitems to be more responsive

### PR DESCRIPTION
**Pull request by elmenqui**
Still missing:
  Functionality of "Forgot Password"
  Functionality of "Remember me"

### CODE REVIEW

**Comment by parpinelopi** [comment]
The layout is very nice, but it does not allow me to register. I have restarted docker and so on, but I was getting the same error.

**Review by mabmalia — CHANGES_REQUESTED** [review]
I am able to login but then can't do anything inside the web application, it seems I am still in the modal box.

Besides that, there are some invalid DOM properties in the code (that can be seen when inspecting the page). When using REACT:
- class should be className;
- for should be htmlFor.

**Comment by elmenqui** [comment]
New commit made fixing the overpossing page once logged in. Also refactored "class" to "className" and "for" to "htmlFor". 

Thanks ya'all

**Review by krismutalapova — APPROVED** [review]
Now everything seems to be working

**Review by mabmalia — APPROVED** [review]
LGTM (more or less).

**Pull request merged**
