### PR TITLE
Styling to LoginPage, LoginFrom, RegistrationForm and Homepage

### PR DESCRIPTION
**Pull request by elmenqui**
When testing the webapp on the projector on Friday it was clear we will need some minor changes on the style:

Changes to Login Page:
* Logo changed to white vector image
* Moved both logo and card down and inner as the will be better displayed in the projector screen
* Changed slogan
* Darkened the card color to also improve visibility on the screen
* Thicken fonts and made most white
* Changed buttons to look and behave as logout button in TopBar
* Modal is now a constant as is in the other pages of the webapp
* Cleaned excess divs

Changes to Registration Form:
* Added Username field that updates TopBar name (fully working)
* Cleaned excess divs
* Made card all have the same look (margin, border) as other modal forms

Changes to HomePage:
* Cleaned excess Divs

App.css:
* Passed some in page styles to app.css when seen that they repeat in other areas 

Overall:
* Organized the code a bit to look tidy

### CODE REVIEW

**Comment by krismutalapova** [comment]
Screenshot 2019-12-15 at 07 46 40

Could you please center the slogan on the login page :)

**Comment by MeriM-dev** [comment]
I find the changes unnecessary, and questionable. 
Gradient was never discussed. 
Like the new slogan, but am not especially impressed by the colour.
The form fields look super weird we need to change them.

**Comment by elmenqui** [comment]
Definately not discussed and hard to know if they will make difference on the presentation but like I wrote when trying the webapp on the projector that we are presenting in the light color and thing letters of the current implementation make it hard to see as there is a lot of light in the area.

The placement of the logo and card are needed as the the screen is way up and we end up with more than 50% of the screen empty and the logo at the very edge.

**Comment by parpinelopi** [comment]
Alberto, the registration fields do not work for me. I try to enter something in the field and it does not respond. Same applies to the button. 

Screenshot 2019-12-15 at 08 28 53

**Review by krismutalapova — APPROVED** [review]
LGTM

**Review by parpinelopi — APPROVED** [review]
LGTM

**Review by mabmalia — APPROVED** [review]
LGTM.

**Pull request merged**
