### PR TITLE
Delete image in a carousel

### PR DESCRIPTION
**Pull request by krismutalapova**
in the item card now when you add pictures you can later delete them by hovering over the picture and  pressing the trash can

### CODE REVIEW

**Review by elmenqui — CHANGES_REQUESTED** [review]
When deleting a photo, the carrousel keeps an empty item but the buttons do not work. If you press anywhere outside the modal and go to another page and back to itemPage -> itemCard then the carrousel is working again with the remaining photos. If another photo is deleted, the same behaviour.

Screenshot 2019-12-13 at 22 30 32

**Comment by krismutalapova** [comment]
it works on my computer as expected - the picture disappears and the next on in carousel is shown 

can someone else pls check the branch? 
I updated it with the latest master

**Comment by krismutalapova** [comment]
I'll slack you the recording of my screen, cannot add here

**Review by elmenqui — APPROVED** [review]
LGTM - Issue reported is now working and items is working as intended. 
GOOD WORK!

**Review by parpinelopi — APPROVED** [review]
Works as it is supposed to. The card though is quite big. :)

**Pull request merged**
