### PR TITLE
Claims page

### PR DESCRIPTION
**Pull request by mabmalia**
* Fixed claims page.
* Added a new field "type" to claims (frontend and backend) so we can present in the claims card the 2 specific fields used in the claims form
* Created the ClaimsCard component and implemented its skeleton (@Pinelopi85 feel free to do all the changes you want, only did it to simplify your work)

ISSUES:
* In the claims form, after pressing "create a claim", we are still in the claims form page. Don't know how to redirect to the claims page (this is the critical issue so far)
* In the claims form, if an item is not selected, the request is rejected by the backend and the claim is not created (not critical since the application is lacking several validations, just so you know).
* the claims form component has some construction issues and warns the user about them if we use inspect (don't know how to fix them)

### CODE REVIEW

**Review by krismutalapova — APPROVED** [review]
Well, good for now I guess
IMPORTANT
to see the item in the claim form first create and item AND choose the insurance for it otherwise claim has no items
and yes we cannot create a claim

**Comment by mabmalia** [comment]
@Kris, you cannot create a claim? You don't see the claim in the claim page? If you click on the nabber?

**Review by parpinelopi — APPROVED** [review]
It works indeed. Good job. I will try to fix the issue of redirecting it to the right page.

**Review by elmenqui — APPROVED** [review]
LGTM - Works and fails where described

**Pull request merged**
